# Generated by Django 2.0 on 2019-12-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_product_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='technology',
            new_name='technology_id',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='technology_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='domain',
            new_name='domain_id',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='technology_name',
            new_name='name',
        ),
    ]
