# Generated by Django 2.0 on 2019-12-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20191218_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='id',
        ),
        migrations.AddField(
            model_name='domain',
            name='_id',
            field=models.CharField(default='000', max_length=200, primary_key=True, serialize=False),
        ),
    ]
