# Generated by Django 2.0 on 2019-12-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20191219_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='technology_id',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='domain_id',
        ),
    ]
