# Generated by Django 2.0 on 2019-12-19 02:36

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20191219_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
